# Generated by Django 3.2.8 on 2021-11-02 06:41

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='youtube_link',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
