# Generated by Django 3.2.8 on 2021-11-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0002_alter_lyric_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='slug',
            field=models.SlugField(default='hello+id', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
