# Generated by Django 3.2.8 on 2021-11-02 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0007_alter_lyric_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyric',
            name='slug',
        ),
    ]
