# Generated by Django 3.2.8 on 2021-11-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0009_lyric_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
