# Generated by Django 3.2.8 on 2021-11-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0011_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='language',
            field=models.CharField(choices=[('arabic', 'Arabic'), ('bangla', 'Bangla'), ('english', 'English'), ('urdu', 'Urdu'), ('mixed', 'Mixed'), ('other', 'Other')], default='Other', max_length=10),
        ),
    ]
