# Generated by Django 3.2.8 on 2021-11-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0013_auto_20211104_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='singer',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
